version: '3.8'
services:
  sqlserver:
    container_name: sql_server_estacio
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "julio102030"
      ACCEPT_EULA: "Y"
    ports:
      - "1533:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
